# Jupyter notebook
---

It's like a text document, but you can run code on it. It can also display inline graphs, pull data from Databases or show excel spreadsheet live.

- In Juputer Notebook everything is a cell
- Each cell contain different types of content: like python code(R or Julia,etc), images or even human readable text (markdown)

```
esc switch to command mode
enter switch to edit mode
m turn to markdown
a inset cell abouve
b insert cell below
dd delete a cell
z undo

Shift+Enter run cell
alt+Enter run cell and add new cell
```

# Python 
---

In [5]:
# comment

In [6]:
# Variable
name = 'Tenzin'
print(name)

Tenzin


In [7]:
age = 30
print(age)

30


In [9]:
# Variable once set will be preserved
print(name, "is", age, "years old")

Tenzin is 30 years old


In [13]:
# Data Types ( int, float, str, bool, )
# an int
age = 30
age


30

In [14]:
type(age)

int

In [15]:
# Floats
price = 2.50
price

2.5

In [16]:
type(price)

float

In [17]:
0.1 * 3

0.30000000000000004

In [19]:
from decimal import Decimal

In [20]:
Decimal('0.1') * 3

Decimal('0.3')

In [22]:
# Strings
print('Hello World') # you can use single or double quote but make sure to match 

Hello World


In [23]:
type('Hello World')

str

In [24]:
len('Tenzin')

6

In [25]:
# Booleans
True

True

In [26]:
type(True)

bool

In [27]:
# None (absence of value)
x = None

In [29]:
print(x)

None


In [32]:
type(x)

NoneType

In [33]:
# type conversion
age ='22'
type(age)

str

In [37]:
age = int(age)

In [38]:
type(age)

int

In [21]:
# Fuction
def add_number(a, b):
    return a + b
add_number(10, 2)

12

In [40]:
# if functin doesn't explicitly include a return statement, Pyhton will return None by default
def empty():
    x = 3
result = empty()
print(result)

None


In [42]:
# we can also define funcitons taht accept variable number of argumens, using star args*:
def add(*args):
    return sum(args)
add(1, 2, 3)

6

In [45]:
# Operators
# add
3 + 3

6

In [46]:
11 % 7

4

In [47]:
2 ** 7

128

In [48]:
3 + 4 * 5

23

In [49]:
3 + 4 * 2 ** 3

35

In [50]:
# Boolean operators
7 > 8

False

In [52]:
8 >= 8

True

In [53]:
True and True

True

In [54]:
not False

True

In [55]:
False or True

True

In [56]:
# If else statement
language = 'python'
if language == 'python':
    print('Let the fun begin!')
else:
    print('you sure?')

Let the fun begin!


In [60]:
# If else elif statements
days = 0
if days >= 30:
    print('Loyal customer')
elif days < 30 & days > 1:
    print('Halfway')
else:
    print('New customer')

New customer


In [62]:
# For loops
names = ['Monica', 'Ross', 'Chandler', 'Joey', 'Rachel']
for name in names:
    print(name)

Monica
Ross
Chandler
Joey
Rachel


In [66]:
# While loops
count = 0
while count < 3:
    print("Counting...",  count+1)
    count += 1

Counting... 1
Counting... 2
Counting... 3


##### Collectins
Python collections are heterogeneous, so you are allowed to multiple types
- lists
- Tuples
- Dictionaries
- Sets

In [67]:
# List []
a_list = [3, 'Tenzin', False]

In [68]:
len(a_list)

3

In [69]:
a_list[1]

'Tenzin'

In [70]:
a_list[-1]

False

In [71]:
a_list.append('python')

In [73]:
'python' in a_list

True

In [74]:
'snake' in a_list

False

In [76]:
# Tuples ()
# Tuples are verysimilar to lists, but they are immuatable. so it cann't be modified
a_tuple = (3, 'Tenzin', 'False')

In [78]:
a_tuple[0]

3

In [79]:
'Tenzin' in a_tuple

True

In [81]:
# error cus immuatable
a_tuple.append('tsundue')

AttributeError: 'tuple' object has no attribute 'append'

In [89]:
# Dictionaries {}
# Dictionaries are mutable and unordered
user = {
    'name' : 'Tenzin',
    'email' : 'tenzin@codewithtenzin.com',
    'age' : 27,
    'developer' : True
}

In [90]:
user

{'name': 'Tsundue',
 'email': 'tenzin@codewithtenzin.com',
 'age': 27,
 'developer': True}

In [92]:
user['email']

'tenzin@codewithtenzin.com'

In [87]:
'age' in user

True

In [88]:
'Tenzin' in user

False

In [102]:
# Sets {}
# sets are unordered collection which the unique characteristic that they only contain unique elements
a_set = {2, 3, 4, 2, 1, 3, 2, 1, 4}
a_set

{1, 2, 3, 4}

In [103]:
# adding elements
a_set.add(10)
a_set

{1, 2, 3, 4, 10}

In [104]:
a_set.pop()
a_set

{2, 3, 4, 10}

In [105]:
# Iterating collections
l = [1, 2, 'three', 'four']

In [106]:
for elem in l:
    print(elem)

1
2
three
four


In [109]:
for key in user:
    print(key.title(), '=>', user[key])

Name => Tsundue
Email => tenzin@codewithtenzin.com
Age => 27
Developer => True


In [111]:
# Modules
# One of the best fearures of Python as a language, is its rich builtin library. To use external modules, you must first import them:

In [113]:
import random
random.randint(0, 99)

13

In [115]:
# Exceptions
# exceptions are raised ata runtime when an abnormal situatin is produced in your program
age = "30"
if age > 20:
    print('Allowed')

TypeError: '>' not supported between instances of 'str' and 'int'

In [117]:
age = '30'
try:
    if age > 20:
        print('Allowed')
except:
    print('Something went wrong')

Something went wrong


In [119]:
try:
    if age > 20:
        print('Allowed')
except TypeError:
    print("Age is probably of a wrong type")

Age is probably of a wrong type


# Numpy
---

- Numpy(Numeric Python) is one of the core packages for numbricalcomputing in Python. Pandas, Matplotlib Statemodels and many other rely on NumPy<br>
- NumPy uses primitive types(floats, ints) which makes storing and computation efficient, while in Python everything is an object.

In [120]:
import sys
import numpy as np

In [121]:
# NumPy arrays
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [122]:
a = np.array([1, 2, 3, 4])

In [123]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [124]:
a[0], a[1]

(1, 2)

In [125]:
a[0:]

array([1, 2, 3, 4])

In [127]:
# 1 to exclusive 3
a[1:3]

array([2, 3])

In [128]:
a[0:-1]

array([1, 2, 3])

In [129]:
a[::2]

array([1, 3])

In [130]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [132]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [134]:
# Array Types
a

array([1, 2, 3, 4])

In [135]:
a.dtype

dtype('int64')

In [136]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [137]:
b.dtype

dtype('float64')

In [138]:
np.array([1, 2, 3, 4], dtype=np.float)

array([1., 2., 3., 4.])

In [139]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [140]:
c = np.array(['a', 'b', 'c'])

In [141]:
c.dtype

dtype('<U1')

In [143]:
d = np.array([{'a' : 1}, sys])

In [145]:
d.dtype

dtype('O')

In [146]:
# Dimension and shapes

In [148]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [149]:
A.shape

(2, 3)

In [150]:
A.ndim

2

In [151]:
A.size

6

In [152]:
B = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [156]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [157]:
B.shape

(2, 2, 3)

In [158]:
B.ndim

3

In [159]:
B.size

12

In [154]:
# indexing
B[1][1]

array([10, 11, 12])

In [155]:
B[0][1][1]

5

In [160]:
# for inconsistent shape
C = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9]
    ]
])

In [161]:
C.shape

(2,)

In [162]:
C.ndim

1

In [163]:
C.size

2

In [164]:
type(C[0])

list

In [167]:
# Indexing and Slicing
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [168]:
A[1]

array([4, 5, 6])

In [176]:
A[1][0]

4

In [177]:
A[1, 0]

4

In [178]:
A[0: 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
A[1:, 1:]

array([[5, 6],
       [8, 9]])

In [180]:
A[1] = np.array([10, 10, 10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [181]:
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [182]:
# Summary statistics
a = np.array([1, 2, 3, 4])

In [183]:
a.sum()

10

In [184]:
a.mean()

2.5

In [185]:
a.std()

1.118033988749895

In [186]:
a.var()

1.25

In [187]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [189]:
A.sum()

45

In [190]:
A.mean()

5.0

In [191]:
A.std()

2.581988897471611

In [193]:
A.sum(axis = 0) #vertical sum

array([12, 15, 18])

In [194]:
A.sum(axis = 1) #horizontal sum

array([ 6, 15, 24])

In [195]:
# Broadcasting and Vecorized operations
a = np.arange(4)

In [196]:
a

array([0, 1, 2, 3])

In [200]:
a + 10

array([10, 11, 12, 13])

In [201]:
a

array([0, 1, 2, 3])

In [203]:
a = a + 10
a

array([20, 21, 22, 23])

In [204]:
b = np.array([10, 10, 10, 10])

In [205]:
a + b

array([30, 31, 32, 33])

In [207]:
# Boolean arrays
# use for masking and filter
a = np.arange(4)
a

array([0, 1, 2, 3])

In [210]:
a[0], a[3]

(0, 3)

In [211]:
a[[True, False, False, True]]

array([0, 3])

In [212]:
a >= 2

array([False, False,  True,  True])

In [213]:
a[a >= 2]

array([2, 3])

In [214]:
a.mean()

1.5

In [215]:
a[a > a.mean()]

array([2, 3])

In [216]:
a[~(a > a.mean())]

array([0, 1])

In [217]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [218]:
a[(a <= 2) & (a% 2 == 0)]

array([0, 2])

In [220]:
A = np.random.randint(100, size=(3, 3))
A

array([[26, 43, 65],
       [67, 28, 17],
       [41, 86, 91]])

In [221]:
A > 30

array([[False,  True,  True],
       [ True, False, False],
       [ True,  True,  True]])

In [223]:
A[A > 30]

array([43, 65, 67, 41, 86, 91])

In [226]:
# Linear Algebra
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [227]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [228]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [229]:
# The @ operator calls the array's __matmul__ method, not dot
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [230]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [231]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [232]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
# Size of objects in Memory

In [233]:
# int, floats
sys.getsizeof(1)

28

In [234]:
# longs are even larger
sys.getsizeof(10**100)

72

In [235]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [237]:
np.dtype(np.int8).itemsize

1

In [238]:
np.dtype(float).itemsize

8

In [240]:
# and for list
sys.getsizeof([1])

72

In [242]:
# numpy list
np.array([1]).nbytes

8

In [246]:
# Performance difference
l = list(range(10000))
a = np.arange(10000)

In [247]:
%time np.sum(a ** 2)

CPU times: user 158 µs, sys: 81 µs, total: 239 µs
Wall time: 174 µs


333283335000

In [248]:
%time sum([x**2 for x in l])

CPU times: user 3.33 ms, sys: 166 µs, total: 3.49 ms
Wall time: 3.5 ms


333283335000

In [249]:
#Useful numpy functions

In [250]:
#random
np.random.random(size = 2)

array([0.06632878, 0.03536621])

In [251]:
np.random.normal(size = 2)

array([-0.97746835,  0.56124967])

In [252]:
np.random.rand(2, 4)

array([[0.99703205, 0.90156396, 0.22981498, 0.64991815],
       [0.6691162 , 0.49842367, 0.62618374, 0.95178854]])

In [253]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [256]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [257]:
# reshape
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [258]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [263]:
#linspace
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [264]:
np.linspace(0, 1, 20, False) # False for exclusive of 1

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [265]:
# zeros, ones, empty
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [266]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [267]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [269]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [271]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [272]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [273]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [275]:
# identity and eye
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [276]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [277]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [278]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [279]:
np.eye(8,4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# Pandas
---